apiVersion: networking.k8s.io/v1
kind: ingress
metadata:
  name: ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/target-type: ip
    
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:eu-north-1:34567898789:certificate/fgvhrfcjsh"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    
    external-dns.alpha.kubernetes.io/hostname: app.tobechanged.com
spec:
  rules:
    - host: app.tobechanged.com
      http:
        paths:
          - path: /
            pathType: prefix
            backend:
              service:
                name: nginx
                port:
                  number: 80
